config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount ActionCable.server => '/cable'
  mount Sidekiq::Web => '/sidekiq'

  resource :session, only: %i[] do
    collection do
      post :login
    end
  end

  resources :users, only: %i[create destroy]
  resources :messages, only: %i[index create]
  resources :groups, only: %i[index show create] do
    resources :members, only: %i[index create]
  end
  resources :posts, only: %i[index create]
end

app/views/chat_users/_user_search_form.html.erb
<%= form_with url: search_chat_users_path, remote: true, method: :get, data: { turbo_frame: 'user_search_result', controller: "user-search" } do |f| %>
  <%= f.text_field :query, hint: "Type to search...", data: { action: "input->user-search#search" } %>
<% end %>

app/views/chat_users/index.html.erb
<% @chat_users.each do |user| %>
  <%= link_to "#{user.name}", "#{messages_path}?receivable_type=#{user.class.name}&receivable_id=#{user.id}" %></div>
<% end %>

app/views/chat_users/search.html.erb
<%= turbo_frame_tag "user_search_page" do %>
  <%= render partial: 'chat_users/user_search_form' %>
  <%= turbo_frame_tag 'user_search_result' do %>
    <% if @users.nil? %>
    <% elsif @users.empty? %>
      <div> Not find </div>
    <% else %>
      <% @users.each do |user| %>
        <div>
          <%= link_to "#{user.email}", "#{messages_path}?receivable_type=#{user.class.name}&receivable_id=#{user.id}", data: { turbo_frame: :chat_page } %>
        </div>
      <% end %>
    <% end %>
  <% end %>
<% end %>